# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff90019265c4a2fdd2759e2fce322cb811bc74434ef4e562b8c787259780db8f2f43f3d8d0fced023950aea9db9b2f616a664dee26297b4f4f80c79c5de49844

test:
  secret_key_base: 93af0bec9d415dba977092b3c8e6f7d497a12b4b5bc119c8504673d5868bddae87045d1c9ffd53ffbbad344d038e7bfb6f7ca2bea285f5e24b86d6b064fb4c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
